name: Auto Update IPTV

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run update script
        run: python update.py

      - name: Commit and push
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "Auto Update & Clean Logs" || echo "No changes"
          git push

